stack-test:
	g++ -std=c++14 -c ../data_structure/stack/stack.cpp stack_test.cpp
	g++ stack.o stack_test.o -o stack_test
	./stack_test -s
	rm *.o stack_test

singly-linked-list-test:
	g++ -std=c++14 -c ../data_structure/singly_linked_list/singly_linked_list.cpp singly_linked_list_test.cpp
	g++ singly_linked_list.o singly_linked_list_test.o -o singly_linked_list_test
	./singly_linked_list_test -s
	rm *.o singly_linked_list_test
