stack-test:
	g++ -std=c++14 -c ../data_structure/stack/stack.cpp stack_test.cpp
	g++ stack.o stack_test.o -o stack_test
	./stack_test -s
	rm *.o stack_test

singly-linked-list-test:
	g++ -std=c++14 -c ../data_structure/singly_linked_list/singly_linked_list.cpp singly_linked_list_test.cpp
	g++ singly_linked_list.o singly_linked_list_test.o -o singly_linked_list_test
	./singly_linked_list_test -s
	rm *.o singly_linked_list_test

doubly-linked-list-test:
	g++ -std=c++14 -c ../data_structure/doubly_linked_list/doubly_linked_list.cpp doubly_linked_list_test.cpp
	g++ -v doubly_linked_list.o doubly_linked_list_test.o -o doubly_linked_list_test
	./doubly_linked_list_test -s
	rm *.o doubly_linked_list_test

heap-test:
	g++ -std=c++14 -c ../data_structure/heap/heap.cpp heap_test.cpp
	g++ heap.o heap_test.o -o heap_test
	./heap_test -s
	rm *.o heap_test

binary-search-tree-test:
	g++ -std=c++14 -c ../data_structure/binary_search_tree/binary_search_tree.cpp binary_search_tree_test.cpp
	g++ bst.o bst_test.o -o bst_test
	./bst_test -s
	rm *.o bst_test

graph-test:
	g++ -std=c++14 -c ../data_structure/graph/graph.cpp graph_test.cpp
	g++ graph.o graph_test.o -o graph_test
	./graph_test -s
	rm *.o graph_test

rle-test:
	g++ -std=c++14 -c ../encoding/rle/rle.cpp rle_encoding_test.cpp
	g++ rle.o rle_encoding_test.o -o rle_test
	./rle_test -s
	rm *.o rle_test
